using QuestPDF.Fluent;
using PayMaster.DTO;

namespace PayMaster
{
    public class PdfReportGenerator
    {
        public static byte[] GeneratePayrollSummaryPdf(List<PayrollSummaryDto> data, int month, int year)
        {
            return Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(20);
                    page.Header().Text($"Payroll Summary - {month}/{year}").FontSize(20).Bold().AlignCenter();
                    page.Content().Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn(2); // Name
                            columns.ConstantColumn(60); // Gross
                            columns.ConstantColumn(60); // PF
                            columns.ConstantColumn(60); // Tax
                            columns.ConstantColumn(60); // Net
                        });

                        table.Header(header =>
                        {
                            header.Cell().Text("Employee").Bold();
                            header.Cell().Text("Gross");
                            header.Cell().Text("PF");
                            header.Cell().Text("Tax");
                            header.Cell().Text("Net");
                        });

                        foreach (var item in data)
                        {
                            table.Cell().Text(item.EmployeeName);
                            table.Cell().Text(item.GrossPay.ToString("F2"));
                            table.Cell().Text(item.EmployeePF.ToString("F2"));
                            table.Cell().Text(item.IncomeTax.ToString("F2"));
                            table.Cell().Text(item.NetPay.ToString("F2"));
                        }
                    });
                    page.Footer().AlignCenter().Text(x => x.Span("Generated by PayMaster • "));
                });
            }).GeneratePdf();
        }
    }
}